import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it, vi } from 'vitest'
import { api, ApiError, type DemoAttackResult, type DemoStatus } from '../api'
import DemoAttack from './DemoAttack'

/**
 * The demo trigger's console behaviour.
 *
 * Two things matter here and the rest is presentation:
 *
 *   1. The control is not offered when the server says it would refuse, and a
 *      destructive-looking action is never one accidental click away.
 *   2. Every number shown comes from the response. The console must not derive a
 *      score, a decision or a signal — one that recomputed them could disagree
 *      with the queue and the audit trail.
 */

const READY: DemoStatus = {
  enabled: true,
  demo_mode: true,
  provider_is_simulated: true,
  scenario: 'fraud_attack',
  attempts: 8,
  window_seconds: 420,
  blocked_because: [],
}

const OFF: DemoStatus = {
  enabled: false,
  demo_mode: false,
  provider_is_simulated: true,
  scenario: 'fraud_attack',
  attempts: 8,
  window_seconds: 420,
  blocked_because: ['FRAUDSHIELD_DEMO_MODE is not enabled'],
}

function attempt(n: number, score: number, decision: DemoAttackResult['results'][number]['decision']) {
  return {
    attempt: n,
    transaction_id: `pay_demo_${n}`,
    order_id: `ord_demo_${n}`,
    at: `2026-08-29T08:3${n}:00+00:00`,
    amount: 20000 + n * 1000,
    payment_method: 'card',
    settlement: 'failed',
    risk_score: score,
    decision,
    sub_scores: { ml: 100, rules: 35, network: 0 },
    fired_rules: n >= 7 ? ['velocity_breach', 'amount_anomaly'] : ['amount_anomaly'],
    override: null,
    txn_count_10m: n - 1,
    amount_ratio: 8.6,
  }
}

const RESULT: DemoAttackResult = {
  scenario: 'fraud_attack',
  demo: true,
  attempts_generated: 8,
  customer_id: 'demo_cust_abc123',
  customer_email: 'demo_fraudster+abc123@example.test',
  device_id: 'demo_shared_device_001',
  ip_hash: 'demo_ip_shared_001',
  window_seconds: 420,
  first_attempt_at: '2026-08-29T08:32:00+00:00',
  last_attempt_at: '2026-08-29T08:39:00+00:00',
  baseline: {
    transactions: 60,
    span_days: 84,
    account_age_days: 96,
    average_amount: 2079.83,
    device_fp: 'demo_home_device_001',
    persisted: false,
    scored: false,
    note: 'in-process context only',
  },
  results: [
    attempt(1, 74, 'BLOCK'),
    attempt(2, 73, 'BLOCK'),
    attempt(3, 73, 'BLOCK'),
    attempt(4, 73, 'BLOCK'),
    attempt(5, 73, 'BLOCK'),
    attempt(6, 73, 'BLOCK'),
    attempt(7, 73.5, 'BLOCK'),
    attempt(8, 77, 'BLOCK'),
  ],
  final_transaction: {
    transaction_id: 'pay_demo_8',
    risk_score: 77,
    decision: 'BLOCK',
    sub_scores: { ml: 100, rules: 35, network: 0 },
    fired_rules: ['velocity_breach', 'amount_anomaly'],
  },
  decisions: { ALLOW: 0, MANUAL_REVIEW: 0, BLOCK: 8 },
  signals: ['amount_anomaly', 'velocity_breach'],
  evidence: { txn_count_10m: 7, device_account_count: 1 },
  thresholds: { review: 5, block: 70 },
  model_version: '2026-08-23T08:06:20+00:00',
  degraded: false,
  transactions_persisted: 8,
  queued_for_review: 8,
  ip_flagged: true,
  notification_triggered: true,
  notifications: { sent: 8 },
  email_provider: 'smtp',
  alerts_enabled: true,
  audit_created: true,
  audit_events: 10,
  creates_ground_truth: false,
  moves_money: false,
  note: 'Synthetic activity generated by the admin-only demo trigger.',
}

describe('demo trigger availability', () => {
  it('offers the control when the server says both gates are open', () => {
    render(<DemoAttack status={READY} />)
    expect(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    ).toBeInTheDocument()
  })

  it('offers no control when demo mode is off, and says so', () => {
    render(<DemoAttack status={OFF} />)
    expect(
      screen.queryByRole('button', { name: /Trigger demo fraud attack/i }),
    ).not.toBeInTheDocument()
    expect(screen.getByText(/demo trigger off/i)).toBeInTheDocument()
  })

  it('renders nothing at all when the backend does not report demo readiness', () => {
    const { container } = render(<DemoAttack status={undefined} />)
    expect(container).toBeEmptyDOMElement()
  })

  it('treats a null status as unavailable rather than enabled', () => {
    const { container } = render(<DemoAttack status={null} />)
    expect(container).toBeEmptyDOMElement()
  })
})

describe('confirmation', () => {
  it('does not call the API on the first click', async () => {
    const spy = vi.spyOn(api, 'demoFraudAttack')
    render(<DemoAttack status={READY} />)

    await userEvent.click(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    )

    expect(spy).not.toHaveBeenCalled()
    expect(screen.getByRole('dialog')).toBeInTheDocument()
    expect(
      screen.getByText(/Generate 8 synthetic suspicious payment attempts\?/i),
    ).toBeInTheDocument()
  })

  it('says no real money is charged and that nothing is cleaned up', async () => {
    render(<DemoAttack status={READY} />)
    await userEvent.click(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    )

    expect(screen.getByText(/does not charge real money/i)).toBeInTheDocument()
    expect(screen.getByText(/not cleaned up/i)).toBeInTheDocument()
  })

  it('generates nothing when the operator cancels', async () => {
    const spy = vi.spyOn(api, 'demoFraudAttack')
    render(<DemoAttack status={READY} />)

    await userEvent.click(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    )
    await userEvent.click(screen.getByRole('button', { name: /^Cancel$/i }))

    expect(spy).not.toHaveBeenCalled()
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })

  it('calls the endpoint once the operator confirms', async () => {
    const spy = vi.spyOn(api, 'demoFraudAttack').mockResolvedValue(RESULT)
    render(<DemoAttack status={READY} />)

    await userEvent.click(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    )
    await userEvent.click(screen.getByRole('button', { name: /Generate 8 attempts/i }))

    await waitFor(() => expect(spy).toHaveBeenCalledTimes(1))
    // No arguments: the attempt count is not the caller's to choose.
    expect(spy).toHaveBeenCalledWith()
  })
})

describe('loading state', () => {
  it('shows progress while the request is in flight and does not freeze', async () => {
    let release: (r: DemoAttackResult) => void = () => {}
    vi.spyOn(api, 'demoFraudAttack').mockReturnValue(
      new Promise<DemoAttackResult>((res) => {
        release = res
      }),
    )
    render(<DemoAttack status={READY} />)

    await userEvent.click(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    )
    await userEvent.click(screen.getByRole('button', { name: /Generate 8 attempts/i }))

    expect(await screen.findByRole('status')).toBeInTheDocument()
    expect(screen.getByText(/Generating eight attempts/i)).toBeInTheDocument()
    // Honest about what the stage list is: one request, not a live trace.
    expect(screen.getByText(/rather than a live trace/i)).toBeInTheDocument()
    // Not dismissable mid-flight.
    expect(screen.queryByRole('button', { name: /^Cancel$/i })).not.toBeInTheDocument()

    release(RESULT)
    await waitFor(() =>
      expect(screen.getByText(/8 attempts generated/i)).toBeInTheDocument(),
    )
  })
})

describe('result summary', () => {
  async function run(result: DemoAttackResult = RESULT) {
    vi.spyOn(api, 'demoFraudAttack').mockResolvedValue(result)
    render(<DemoAttack status={READY} />)
    await userEvent.click(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    )
    await userEvent.click(screen.getByRole('button', { name: /Generate 8 attempts/i }))
    await waitFor(() =>
      expect(screen.getByText(/8 attempts generated/i)).toBeInTheDocument(),
    )
  }

  it('reports the score and decision the server returned', async () => {
    await run()
    expect(screen.getByText('77')).toBeInTheDocument()
    expect(screen.getAllByText('BLOCK').length).toBeGreaterThan(0)
  })

  it('reports the signals that actually fired, not a fixed list', async () => {
    await run()
    expect(screen.getByText(/amount_anomaly, velocity_breach/)).toBeInTheDocument()
  })

  it('reports the velocity the engine saw', async () => {
    await run()
    expect(screen.getByText(/7 attempts in 10 minutes/i)).toBeInTheDocument()
  })

  it('lists every generated attempt with its own score', async () => {
    await run()
    const rows = screen.getAllByRole('row')
    // Eight attempts plus the header row.
    expect(rows).toHaveLength(9)
    expect(screen.getByText('74')).toBeInTheDocument()
  })

  it('reports the email outcome in the notification system\u2019s own terms', async () => {
    await run()
    expect(screen.getByText(/smtp: 8 sent/i)).toBeInTheDocument()
  })

  it('does not call a skipped alert a failure', async () => {
    await run({
      ...RESULT,
      notifications: { skipped: 8 },
      email_provider: 'console',
      alerts_enabled: false,
    })
    expect(screen.getByText(/console: 8 skipped \(no recipients\)/i)).toBeInTheDocument()
    expect(screen.queryByText(/failed/i)).not.toBeInTheDocument()
  })

  it('reports the audit trail and the queue', async () => {
    await run()
    expect(screen.getByText(/recorded \(10 events\)/i)).toBeInTheDocument()
    expect(screen.getByText(/8 of 8 queued/i)).toBeInTheDocument()
  })

  it('reports an ALLOW verdict as ALLOW rather than dressing it up', async () => {
    await run({
      ...RESULT,
      results: RESULT.results.map((r) => ({ ...r, risk_score: 3.3, decision: 'ALLOW' as const })),
      final_transaction: { ...RESULT.final_transaction, risk_score: 3.3, decision: 'ALLOW' },
      decisions: { ALLOW: 8, MANUAL_REVIEW: 0, BLOCK: 0 },
      queued_for_review: 0,
      signals: [],
      notification_triggered: false,
      notifications: {},
    })
    expect(screen.getAllByText('ALLOW').length).toBeGreaterThan(0)
    expect(screen.queryByText('BLOCK')).not.toBeInTheDocument()
    expect(screen.getByText(/0 of 8 queued/i)).toBeInTheDocument()
    expect(screen.getByText(/nothing alertable/i)).toBeInTheDocument()
  })

  it('shows the thresholds in force, so a reader can check the band', async () => {
    await run()
    expect(screen.getByText(/review 5, block 70/i)).toBeInTheDocument()
  })
})

describe('queue refresh', () => {
  it('refreshes the console after a successful run', async () => {
    vi.spyOn(api, 'demoFraudAttack').mockResolvedValue(RESULT)
    const onGenerated = vi.fn()
    render(<DemoAttack status={READY} onGenerated={onGenerated} />)

    await userEvent.click(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    )
    await userEvent.click(screen.getByRole('button', { name: /Generate 8 attempts/i }))

    await waitFor(() => expect(onGenerated).toHaveBeenCalledTimes(1))
  })

  it('does not refresh when the run failed', async () => {
    vi.spyOn(api, 'demoFraudAttack').mockRejectedValue(
      new ApiError('The demo fraud attack is disabled.', 403),
    )
    const onGenerated = vi.fn()
    render(<DemoAttack status={READY} onGenerated={onGenerated} />)

    await userEvent.click(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    )
    await userEvent.click(screen.getByRole('button', { name: /Generate 8 attempts/i }))

    await waitFor(() =>
      expect(screen.getByRole('alert')).toHaveTextContent(/disabled/i),
    )
    expect(onGenerated).not.toHaveBeenCalled()
  })
})

describe('error state', () => {
  it('reports the server\u2019s refusal and offers the control again', async () => {
    vi.spyOn(api, 'demoFraudAttack').mockRejectedValue(
      new ApiError('refuses to run unless the payment provider is the simulator', 409),
    )
    render(<DemoAttack status={READY} />)

    await userEvent.click(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    )
    await userEvent.click(screen.getByRole('button', { name: /Generate 8 attempts/i }))

    await waitFor(() =>
      expect(screen.getByRole('alert')).toHaveTextContent(/simulator/i),
    )
    // Back to idle: no half-finished run left on screen.
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    ).toBeEnabled()
  })

  it('survives a non-ApiError failure without crashing', async () => {
    vi.spyOn(api, 'demoFraudAttack').mockRejectedValue(new Error('network down'))
    render(<DemoAttack status={READY} />)

    await userEvent.click(
      screen.getByRole('button', { name: /Trigger demo fraud attack/i }),
    )
    await userEvent.click(screen.getByRole('button', { name: /Generate 8 attempts/i }))

    await waitFor(() =>
      expect(screen.getByRole('alert')).toHaveTextContent(/network down/i),
    )
  })
})
